#ChipScope Core Inserter Project File Version 3.0
#Tue Nov 24 19:22:22 SGT 2020
Project.device.designInputFile=F\:\\STEE_PROJ\\CONV\\OpalKelly3010_Verilog_CNN\\working_dir\\testing_CNN_dbg_cs.ngc
Project.device.designOutputFile=F\:\\STEE_PROJ\\CONV\\OpalKelly3010_Verilog_CNN\\working_dir\\testing_CNN_dbg_cs.ngc
Project.device.deviceFamily=6
Project.device.enableRPMs=true
Project.device.outputDirectory=F\:\\STEE_PROJ\\CONV\\OpalKelly3010_Verilog_CNN\\working_dir\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=clk_trig*
Project.filter<10>=poa2_data
Project.filter<11>=read_cnn_data_out
Project.filter<12>=done*
Project.filter<13>=parallel*
Project.filter<14>=done
Project.filter<15>=parallel
Project.filter<16>=mem_addr*
Project.filter<17>=mem_addr1
Project.filter<18>=meme_addr1
Project.filter<1>=
Project.filter<2>=*done*
Project.filter<3>=*read_cnn_data_out*
Project.filter<4>=*poa2*
Project.filter<5>=*clk*
Project.filter<6>=*clk_trig*
Project.filter<7>=*sys_clk1*
Project.filter<8>=sys_clk1
Project.filter<9>=poa*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=clk_trig
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=clk_div
Project.unit<0>.dataChannel<10>=ext_mem_0 addra<6>
Project.unit<0>.dataChannel<11>=ext_mem_0 addra<7>
Project.unit<0>.dataChannel<12>=ext_mem_0 addra<8>
Project.unit<0>.dataChannel<13>=ext_mem_0 addra<9>
Project.unit<0>.dataChannel<14>=ext_mem_0 addra<10>
Project.unit<0>.dataChannel<15>=ext_mem_0 addra<11>
Project.unit<0>.dataChannel<16>=ext_mem_0 addra<12>
Project.unit<0>.dataChannel<17>=ext_mem_0 addra<13>
Project.unit<0>.dataChannel<18>=ext_mem_0 addra<14>
Project.unit<0>.dataChannel<19>=ext_mem_0 addra<15>
Project.unit<0>.dataChannel<1>=ext_mem_0 wea<0>
Project.unit<0>.dataChannel<20>=ext_mem_0 addra<16>
Project.unit<0>.dataChannel<21>=ext_mem_1 dina<0>
Project.unit<0>.dataChannel<22>=ext_mem_1 douta<0>
Project.unit<0>.dataChannel<23>=ext_mem_1 wea<0>
Project.unit<0>.dataChannel<24>=ext_mem_1 addra<0>
Project.unit<0>.dataChannel<25>=ext_mem_1 addra<1>
Project.unit<0>.dataChannel<26>=ext_mem_1 addra<2>
Project.unit<0>.dataChannel<27>=ext_mem_1 addra<3>
Project.unit<0>.dataChannel<28>=ext_mem_1 addra<4>
Project.unit<0>.dataChannel<29>=ext_mem_1 addra<5>
Project.unit<0>.dataChannel<2>=ext_mem_0 dina<0>
Project.unit<0>.dataChannel<30>=ext_mem_1 addra<6>
Project.unit<0>.dataChannel<31>=ext_mem_1 addra<7>
Project.unit<0>.dataChannel<32>=ext_mem_1 addra<8>
Project.unit<0>.dataChannel<33>=ext_mem_1 addra<9>
Project.unit<0>.dataChannel<34>=ext_mem_1 addra<10>
Project.unit<0>.dataChannel<35>=ext_mem_1 addra<11>
Project.unit<0>.dataChannel<36>=ext_mem_1 addra<12>
Project.unit<0>.dataChannel<37>=ext_mem_1 addra<13>
Project.unit<0>.dataChannel<38>=ext_mem_1 addra<14>
Project.unit<0>.dataChannel<39>=ext_mem_1 addra<15>
Project.unit<0>.dataChannel<3>=ext_mem_0 douta<0>
Project.unit<0>.dataChannel<40>=ext_mem_1 addra<16>
Project.unit<0>.dataChannel<41>=poa2_data<0>
Project.unit<0>.dataChannel<42>=poa2_data<1>
Project.unit<0>.dataChannel<43>=poa2_data<2>
Project.unit<0>.dataChannel<44>=poa2_data<3>
Project.unit<0>.dataChannel<45>=poa2_data<4>
Project.unit<0>.dataChannel<46>=poa2_data<5>
Project.unit<0>.dataChannel<47>=poa2_data<6>
Project.unit<0>.dataChannel<48>=poa2_data<7>
Project.unit<0>.dataChannel<49>=parallel_out_0_IBUF
Project.unit<0>.dataChannel<4>=ext_mem_0 addra<0>
Project.unit<0>.dataChannel<50>=parallel_out_1_IBUF
Project.unit<0>.dataChannel<51>=parallel_out_2_IBUF
Project.unit<0>.dataChannel<52>=parallel_out_3_IBUF
Project.unit<0>.dataChannel<53>=parallel_out_4_IBUF
Project.unit<0>.dataChannel<54>=parallel_out_5_IBUF
Project.unit<0>.dataChannel<55>=parallel_out_6_IBUF
Project.unit<0>.dataChannel<56>=parallel_out_7_IBUF
Project.unit<0>.dataChannel<57>=done_IBUF
Project.unit<0>.dataChannel<58>=read_cnn_data_out
Project.unit<0>.dataChannel<5>=ext_mem_0 addra<1>
Project.unit<0>.dataChannel<6>=ext_mem_0 addra<2>
Project.unit<0>.dataChannel<7>=ext_mem_0 addra<3>
Project.unit<0>.dataChannel<8>=ext_mem_0 addra<4>
Project.unit<0>.dataChannel<9>=ext_mem_0 addra<5>
Project.unit<0>.dataDepth=2048
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=59
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=clk_div
Project.unit<0>.triggerChannel<0><1>=ext_mem_0 wea<0>
Project.unit<0>.triggerChannel<0><2>=ext_mem_0 dina<0>
Project.unit<0>.triggerChannel<0><3>=ext_mem_0 douta<0>
Project.unit<0>.triggerChannel<1><0>=ext_mem_0 addra<0>
Project.unit<0>.triggerChannel<1><10>=ext_mem_0 addra<10>
Project.unit<0>.triggerChannel<1><11>=ext_mem_0 addra<11>
Project.unit<0>.triggerChannel<1><12>=ext_mem_0 addra<12>
Project.unit<0>.triggerChannel<1><13>=ext_mem_0 addra<13>
Project.unit<0>.triggerChannel<1><14>=ext_mem_0 addra<14>
Project.unit<0>.triggerChannel<1><15>=ext_mem_0 addra<15>
Project.unit<0>.triggerChannel<1><16>=ext_mem_0 addra<16>
Project.unit<0>.triggerChannel<1><1>=ext_mem_0 addra<1>
Project.unit<0>.triggerChannel<1><2>=ext_mem_0 addra<2>
Project.unit<0>.triggerChannel<1><3>=ext_mem_0 addra<3>
Project.unit<0>.triggerChannel<1><4>=ext_mem_0 addra<4>
Project.unit<0>.triggerChannel<1><5>=ext_mem_0 addra<5>
Project.unit<0>.triggerChannel<1><6>=ext_mem_0 addra<6>
Project.unit<0>.triggerChannel<1><7>=ext_mem_0 addra<7>
Project.unit<0>.triggerChannel<1><8>=ext_mem_0 addra<8>
Project.unit<0>.triggerChannel<1><9>=ext_mem_0 addra<9>
Project.unit<0>.triggerChannel<2><0>=ext_mem_1 dina<0>
Project.unit<0>.triggerChannel<2><1>=ext_mem_1 douta<0>
Project.unit<0>.triggerChannel<2><2>=ext_mem_1 wea<0>
Project.unit<0>.triggerChannel<3><0>=ext_mem_1 addra<0>
Project.unit<0>.triggerChannel<3><10>=ext_mem_1 addra<10>
Project.unit<0>.triggerChannel<3><11>=ext_mem_1 addra<11>
Project.unit<0>.triggerChannel<3><12>=ext_mem_1 addra<12>
Project.unit<0>.triggerChannel<3><13>=ext_mem_1 addra<13>
Project.unit<0>.triggerChannel<3><14>=ext_mem_1 addra<14>
Project.unit<0>.triggerChannel<3><15>=ext_mem_1 addra<15>
Project.unit<0>.triggerChannel<3><16>=ext_mem_1 addra<16>
Project.unit<0>.triggerChannel<3><1>=ext_mem_1 addra<1>
Project.unit<0>.triggerChannel<3><2>=ext_mem_1 addra<2>
Project.unit<0>.triggerChannel<3><3>=ext_mem_1 addra<3>
Project.unit<0>.triggerChannel<3><4>=ext_mem_1 addra<4>
Project.unit<0>.triggerChannel<3><5>=ext_mem_1 addra<5>
Project.unit<0>.triggerChannel<3><6>=ext_mem_1 addra<6>
Project.unit<0>.triggerChannel<3><7>=ext_mem_1 addra<7>
Project.unit<0>.triggerChannel<3><8>=ext_mem_1 addra<8>
Project.unit<0>.triggerChannel<3><9>=ext_mem_1 addra<9>
Project.unit<0>.triggerChannel<4><0>=poa2_data<0>
Project.unit<0>.triggerChannel<4><1>=poa2_data<1>
Project.unit<0>.triggerChannel<4><2>=poa2_data<2>
Project.unit<0>.triggerChannel<4><3>=poa2_data<3>
Project.unit<0>.triggerChannel<4><4>=poa2_data<4>
Project.unit<0>.triggerChannel<4><5>=poa2_data<5>
Project.unit<0>.triggerChannel<4><6>=poa2_data<6>
Project.unit<0>.triggerChannel<4><7>=poa2_data<7>
Project.unit<0>.triggerChannel<5><0>=parallel_out_0_IBUF
Project.unit<0>.triggerChannel<5><1>=parallel_out_1_IBUF
Project.unit<0>.triggerChannel<5><2>=parallel_out_2_IBUF
Project.unit<0>.triggerChannel<5><3>=parallel_out_3_IBUF
Project.unit<0>.triggerChannel<5><4>=parallel_out_4_IBUF
Project.unit<0>.triggerChannel<5><5>=parallel_out_5_IBUF
Project.unit<0>.triggerChannel<5><6>=parallel_out_6_IBUF
Project.unit<0>.triggerChannel<5><7>=parallel_out_7_IBUF
Project.unit<0>.triggerChannel<6><0>=done_IBUF
Project.unit<0>.triggerChannel<6><1>=read_cnn_data_out
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCount<4>=1
Project.unit<0>.triggerMatchCount<5>=1
Project.unit<0>.triggerMatchCount<6>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchCountWidth<4><0>=0
Project.unit<0>.triggerMatchCountWidth<5><0>=0
Project.unit<0>.triggerMatchCountWidth<6><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerMatchType<4><0>=1
Project.unit<0>.triggerMatchType<5><0>=1
Project.unit<0>.triggerMatchType<6><0>=1
Project.unit<0>.triggerPortCount=7
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortIsData<4>=true
Project.unit<0>.triggerPortIsData<5>=true
Project.unit<0>.triggerPortIsData<6>=true
Project.unit<0>.triggerPortWidth<0>=4
Project.unit<0>.triggerPortWidth<1>=17
Project.unit<0>.triggerPortWidth<2>=3
Project.unit<0>.triggerPortWidth<3>=17
Project.unit<0>.triggerPortWidth<4>=8
Project.unit<0>.triggerPortWidth<5>=8
Project.unit<0>.triggerPortWidth<6>=2
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
